version: '3.5'
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS="host.docker.internal"
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
networks:
  default:
    name: shared
    external: true
